import base64
import requests


class Classifier:
    def __init__(
        self, model_url="http://localhost:11434/api/generate", model_name="gemma3"
    ):
        self.model_url = model_url
        self.model_name = model_name
        self.categories = [
            "Road",
            "Garbage",
            "Water",
            "Electricity",
            "Trees",
            "Street Light",
        ]

        with open("information.txt", "r") as file:
            self.information = file.read()

    def encode_image(self, image_path):
        with open(image_path, "rb") as img:
            return base64.b64encode(img.read()).decode("utf-8")

    def department_selection(self, image_path, image_description=None, category=None):
        image_data = self.encode_image(image_path)

        prompt = f"""
            {self.information}
            Image Captions according to user: {image_description}
            The user description might sometimes be incomplete or faulty
            Issue Category (Can trust because it is generated by the model if not None): {category}
        """

        response = requests.post(
            self.model_url,
            json={
                "model": self.model_name,
                "prompt": prompt,
                "images": [image_data],
                "stream": False,
            },
        )

        return response.json()["response"].strip()

    def categorize(self, image_path, image_description=None):
        image_data = self.encode_image(image_path)
        prompt = f"""
        You are an expert image classifier. Analyze the provided image and classify it into exactly ONE of the following categories:
        {', '.join(self.categories)}.
        if some of the image does not match with the category given, then print Invalid Image
        Only respond with the category name. No explanations or extra text.
        Image Captions according to user: {image_description}
        The user description might sometimes be incomplete or faulty
        """
        res = requests.post(
            "http://localhost:11434/api/generate",
            json={
                "model": "gemma3",
                "prompt": prompt,
                "images": [image_data],
                "stream": False,
            },
        )

        return res.json()["response"].strip()
